FAIL_TO_PASS:
- TestLexer
PASS_TO_PASS:
- TestDispenser_Val_Next
- TestDispenser_NextArg
- TestDispenser_NextLine
- TestDispenser_NextBlock
- TestDispenser_Args
- TestDispenser_RemainingArgs
- TestDispenser_ArgErr_Err
- TestFormatter
- TestParseVariadic
- TestAllTokens
- TestParseOneAndImport
- TestRecursiveImport
- TestDirectiveImport
- TestParseAll
- TestEnvironmentReplacement
- TestImportReplacementInJSONWithBrace
- TestSnippets
- TestImportedFilesIgnoreNonDirectiveImportTokens
- TestSnippetAcrossMultipleFiles
base_commit: 4181c79a8130a59c40c76437e15265452422ccb1
created_at: '2024-01-18 22:01:13'
eval_type: pass_and_fail
hints_text: Yeah you're right we should probably allow fully blank lines. I'll look
  into that soon. (Unless someone gets to it before me, PRs welcome)
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-6051:latest
instance_id: caddyserver__caddy-6051
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '6051'
