base_commit: 09acf64155c16dc6f580f36569ae89344e9734a3
created_at: '2023-01-09 17:28:43'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-2752:latest
instance_id: briannesbitt__carbon-2752
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '2752'
