base_commit: 310459370ad8bb9c0b574735dcca4868a5f05803
created_at: '2021-08-08 13:35:12'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jekyll_1776_jekyll-8761:latest
instance_id: jekyll__jekyll-8761
log_parser: parse_log_jekyll
repo: jekyll/jekyll
split: test
version: '8761'
