base_commit: 40203ff6cb18c9fff9f605ba78f21ce95fd04d6c
created_at: '2023-05-16 14:02:51'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-3570:latest
instance_id: phpoffice__phpspreadsheet-3570
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '3570'
