base_commit: 5cfd28d476c6859617878f951931b8ce7d36b9df
created_at: '2023-11-27 03:14:35'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-3729:latest
instance_id: fmtlib__fmt-3729
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '3729'
