base_commit: b40636742533721d55a434838830e30d57889aef
created_at: '2024-07-26 15:33:12'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-4114:latest
instance_id: phpoffice__phpspreadsheet-4114
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '4114'
