base_commit: 826207ac6996fc1cf433e18476cf898e33c4aa06
created_at: '2023-12-29 01:41:39'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-7635:latest
instance_id: php-cs-fixer__php-cs-fixer-7635
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '7635'
