base_commit: dfe5b12c08dfa803fe5a275b380991df25f4b52d
created_at: '2024-02-23 19:53:02'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-3863:latest
instance_id: fmtlib__fmt-3863
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '3863'
