FAIL_TO_PASS:
- ranges_test.format_vector
PASS_TO_PASS:
- ranges_test.format_array
- ranges_test.format_2d_array
- ranges_test.format_array_of_literals
- ranges_test.format_nested_vector
- ranges_test.to_string_vector
- ranges_test.format_map
- ranges_test.format_set
- ranges_test.format_flat_set
- ranges_test.format_adl_begin_end
- ranges_test.format_pair
- ranges_test.format_tuple
- ranges_test.tuple_parse_calls_element_parse
- ranges_test.format_struct
- ranges_test.format_to
- ranges_test.disabled_range_formatting_of_path
- ranges_test.range
- ranges_test.enum_range
- ranges_test.unformattable_range
- ranges_test.join
- ranges_test.join_bytes
- ranges_test.join_tuple
- ranges_test.join_initializer_list
- ranges_test.join_sentinel
- ranges_test.join_range
- ranges_test.format_join_adl_begin_end
- ranges_test.is_printable
- ranges_test.escape
- ranges_test.range_of_range_of_mixed_const
- ranges_test.vector_char
- ranges_test.container_adaptor
- ranges_test.format_as_tie
- ranges_test.lvalue_qualified_begin_end
- ranges_odr_test.format_vector
base_commit: dfe5b12c08dfa803fe5a275b380991df25f4b52d
created_at: '2024-02-23 19:53:02'
eval_type: pass_and_fail
hints_text: The `s` format specifier for ranges is not supported yet.
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-3863:latest
instance_id: fmtlib__fmt-3863
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '3863'
