base_commit: 37d48c45e0e2496c3acecee431416c1d1aab52bb
created_at: '2024-12-16 11:21:23'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-53914:latest
instance_id: laravel__framework-53914
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '53914'
