base_commit: c5cde0cf7542234dc061af8a25f77fcdad430e35
created_at: '2024-01-02 19:38:30'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-7663:latest
instance_id: php-cs-fixer__php-cs-fixer-7663
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '7663'
