base_commit: fed4fea217abbc502f2e823465de903c8f2b623d
created_at: '2023-07-31 12:06:17'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.burntsushi_1776_ripgrep-2576:latest
instance_id: burntsushi__ripgrep-2576
log_parser: parse_log_cargo
repo: burntsushi/ripgrep
split: test
version: '2576'
