base_commit: c6cce43cd94489f655f4488c5a50ecaf781c94f2
created_at: '2024-08-12 15:14:58'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.axios_1776_axios-6539:latest
instance_id: axios__axios-6539
log_parser: parse_log_tap
repo: axios/axios
split: test
version: '6539'
