base_commit: d2867c02472185f610a49cff1cf39c491df1039b
created_at: '2021-07-24 16:12:49'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fluent_1776_fluentd-3466:latest
instance_id: fluent__fluentd-3466
log_parser: parse_log_ruby_unit
repo: fluent/fluentd
split: test
version: '3466'
