FAIL_TO_PASS:
- PrintfTest.MinusFlag
PASS_TO_PASS:
- PrintfTest.NoArgs
- PrintfTest.Escape
- PrintfTest.PositionalArgs
- PrintfTest.AutomaticArgIndexing
- PrintfTest.NumberIsTooBigInArgIndex
- PrintfTest.SwitchArgIndexing
- PrintfTest.InvalidArgIndex
- PrintfTest.DefaultAlignRight
- PrintfTest.ZeroFlag
- PrintfTest.PlusFlag
- PrintfTest.SpaceFlag
- PrintfTest.HashFlag
- PrintfTest.Width
- PrintfTest.DynamicWidth
- PrintfTest.IntPrecision
- PrintfTest.FloatPrecision
- PrintfTest.StringPrecision
- PrintfTest.IgnorePrecisionForNonNumericArg
- PrintfTest.DynamicPrecision
- PrintfTest.Length
- PrintfTest.Bool
- PrintfTest.Int
- PrintfTest.long_long
- PrintfTest.Float
- PrintfTest.Inf
- PrintfTest.Char
- PrintfTest.String
- PrintfTest.UCharString
- PrintfTest.Pointer
- PrintfTest.Location
- PrintfTest.Enum
- PrintfTest.Examples
- PrintfTest.PrintfError
- PrintfTest.WideString
- PrintfTest.PrintfCustom
- PrintfTest.OStream
- PrintfTest.VPrintf
- PrintfTest.CheckFormatStringRegression
- PrintfTest.FixedLargeExponent
- PrintfTest.VSPrintfMakeArgsExample
- PrintfTest.VSPrintfMakeWArgsExample
- PrintfTest.CustomFormat
base_commit: 981b517ccf2d91bf3bf52c518ac43710b57b5e17
created_at: '2020-05-14 14:49:55'
eval_type: pass_and_fail
hints_text: "> why fmt::sprintf ignores the minus flag when formatting a char\r\n\r\
  \nNo good reason. This needs to be fixed (in code, not documentation). A PR is welcome."
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-1683:latest
instance_id: fmtlib__fmt-1683
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '1683'
