base_commit: eacaa25dca01b79b9b468184c452b97ad0b30dd7
created_at: '2025-01-10 07:18:11'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-4313:latest
instance_id: phpoffice__phpspreadsheet-4313
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '4313'
