FAIL_TO_PASS:
- org.apache.druid.timeline.VersionedIntervalTimelineTest#testOverlapSecondContainsFirstZeroLengthInterval
- org.apache.druid.timeline.VersionedIntervalTimelineTest#testOverlapSecondContainsFirstZeroLengthInterval2
- org.apache.druid.timeline.VersionedIntervalTimelineTest#testOverlapSecondContainsFirstZeroLengthInterval3
PASS_TO_PASS:
- org.apache.druid.timeline.VersionedIntervalTimelineTest#testOverlapFirstContainsSecond
- org.apache.druid.timeline.VersionedIntervalTimelineTest#testOverlapSecondContainsFirst
base_commit: a7d4162195a630c380d75516c24229cc23e25271
created_at: '2023-04-20 22:54:25'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.apache_1776_druid-14136:latest
instance_id: apache__druid-14136
log_parser: parse_log_maven
repo: apache/druid
split: test
version: '14136'
