base_commit: ab53bf0c4727ae63c6a3a3d772b7bd837d2f49c3
created_at: '2024-08-06 13:16:59'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_tokio-6752:latest
instance_id: tokio-rs__tokio-6752
log_parser: parse_log_cargo
repo: tokio-rs/tokio
split: test
version: '6752'
