base_commit: b17a932342bfdeeaf1dc0fbe4f436c83e258d6c8
created_at: '2020-09-19 09:38:08'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-2757:latest
instance_id: preactjs__preact-2757
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '2757'
