base_commit: d481d8d69a94dc00e5c1b147ec1f7e7492626b12
created_at: '2024-11-07 17:38:38'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-3103:latest
instance_id: briannesbitt__carbon-3103
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '3103'
