base_commit: 5ed0ce8bbbc50843f4a63b47ed7004326e546697
created_at: '2024-06-23 08:21:53'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-51890:latest
instance_id: laravel__framework-51890
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '51890'
