base_commit: 9b3f2055288f3166374e02f2636071a959b1bf37
created_at: '2024-03-09 19:09:47'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-3940:latest
instance_id: phpoffice__phpspreadsheet-3940
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '3940'
