base_commit: 5ec1b4baaf01dae0b22567db53886c83b74e0e76
created_at: '2023-01-17 19:39:09'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prometheus_1776_prometheus-11859:latest
instance_id: prometheus__prometheus-11859
log_parser: parse_log_gotest
repo: prometheus/prometheus
split: test
version: '11859'
