base_commit: 0c8a80e83470bd4e042c500955684cad6f76b19f
created_at: '2024-02-15 05:22:52'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-3903:latest
instance_id: phpoffice__phpspreadsheet-3903
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '3903'
