FAIL_TO_PASS:
- String Helper > Issue 3900
PASS_TO_PASS:
- String Helper > Get is iconv enabled
- String Helper > Get decimal separator
- String Helper > Set decimal separator
- String Helper > Get thousands separator
- String Helper > Set thousands separator
- String Helper > Get currency code
- String Helper > Set currency code
- String Helper > Control character p h p 2 o o x m l
- String Helper > Control character o o x m l 2 p h p
- String Helper > S y l kto u t f 8
base_commit: 0c8a80e83470bd4e042c500955684cad6f76b19f
created_at: '2024-02-15 05:22:52'
eval_type: pass_and_fail
hints_text: "Will fix reproduce code in a moment :)\r\n\r\nedit. And now fixed"
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-3903:latest
instance_id: phpoffice__phpspreadsheet-3903
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '3903'
