base_commit: 418fdc98d631cfb52333c7aeae80c43c4a68d13a
created_at: '2025-01-10 11:02:27'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.rubocop_1776_rubocop-13668:latest
instance_id: rubocop__rubocop-13668
log_parser: parse_log_rspec_transformed_json
repo: rubocop/rubocop
split: test
version: '13668'
