base_commit: 6f7ff8556587d51c6919a864926e4b8090f92c3f
created_at: '2023-07-16 00:13:44'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_axum-2096:latest
instance_id: tokio-rs__axum-2096
log_parser: parse_log_cargo
repo: tokio-rs/axum
split: test
version: '2096'
