base_commit: 060cce0a910ffd9dc4e92efbe758fc5f187c3145
created_at: '2024-04-04 20:37:29'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.gohugoio_1776_hugo-12343:latest
instance_id: gohugoio__hugo-12343
log_parser: parse_log_gotest
repo: gohugoio/hugo
split: test
version: '12343'
