base_commit: 1d762cbdb379838b10bde0a5a901c5b5c2a83437
created_at: '2024-03-27 11:30:56'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-2981:latest
instance_id: briannesbitt__carbon-2981
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '2981'
