base_commit: c077b95ba2dcaafee39e302cc086bf99fa9248d0
created_at: '2023-07-05 16:28:49'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jqlang_1776_jq-2658:latest
instance_id: jqlang__jq-2658
log_parser: parse_log_jq
repo: jqlang/jq
split: test
version: '2658'
