base_commit: 37a7ea2cdceae530d79197d887a347a877cd3dd4
created_at: '2024-06-19 17:27:35'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.faker-ruby_1776_faker-2970:latest
instance_id: faker-ruby__faker-2970
log_parser: parse_log_ruby_unit
repo: faker-ruby/faker
split: test
version: '2970'
