base_commit: 85740c3e7a1fa48346dfcbd4497f463ccb1c1b05
created_at: '2022-10-10 15:26:26'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.axios_1776_axios-5085:latest
instance_id: axios__axios-5085
log_parser: parse_log_tap
repo: axios/axios
split: test
version: '5085'
