base_commit: b820d8b73eade8bc5b3fbf7e5fe0dd5150de80e2
created_at: '2024-03-21 11:31:39'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-4316:latest
instance_id: preactjs__preact-4316
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '4316'
