FAIL_TO_PASS:
- ranges_test.join_tuple
PASS_TO_PASS:
- ranges_test.format_array
- ranges_test.format_2d_array
- ranges_test.format_array_of_literals
- ranges_test.format_vector
- ranges_test.format_vector2
- ranges_test.format_map
- ranges_test.format_pair
- ranges_test.format_tuple
- ranges_test.format_struct
- ranges_test.format_to
- ranges_test.path_like
- ranges_test.range
- ranges_test.unformattable_range
- ranges_test.join_initializer_list
- ranges_test.join_sentinel
- ranges_test.join_range
- ranges_test.is_printable
- ranges_test.escape_string
base_commit: 4b8bda25c05d9f959ffed9a0580f0ded623177e5
created_at: '2021-08-18 08:18:23'
eval_type: pass_and_fail
hints_text: "> I'd expect the given format specifier to be applied to each element\
  \ in the tuple. An exception would only be thrown if the format specifier didn't\
  \ make sense for one of the tuple's types.\r\n\r\nThat's an interesting idea. A\
  \ PR would be welcome."
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-2457:latest
instance_id: fmtlib__fmt-2457
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '2457'
