FAIL_TO_PASS:
- LPOP/RPOP with <count> against non existing key in RESP2
PASS_TO_PASS:
- RPOP/LPOP with the optional count argument
- LPOP/RPOP with the count 0 returns an empty array in RESP3
- LPOP/RPOP against non existing key in RESP3
- LPOP/RPOP with <count> against non existing key in RESP3
- LPOP/RPOP with the count 0 returns an empty array in RESP2
- LPOP/RPOP against non existing key in RESP2
- MULTI/EXEC is isolated from the point of view of BLPOP
- Basic LPOP/RPOP/LMPOP - linkedlist
- Basic LPOP/RPOP/LMPOP - ziplist
- LPOP/RPOP/LMPOP against empty list
- LPOP/RPOP/LMPOP NON-BLOCK or BLOCK against non list value
- Mass RPOP/LPOP - quicklist
base_commit: 1e25bdf7808bb400f2dc552ec0d6690d1b340d23
created_at: '2022-01-10 16:51:11'
eval_type: pass_and_fail
hints_text: "looks like you're right.\r\nthis is a bug in redis 6.2 when COUNT was\
  \ added\r\n\r\n```diff\r\n-    robj *o = lookupKeyWriteOrReply(c, c->argv[1], shared.null[c->resp]);\r\
  \n+    robj *o = lookupKeyWriteOrReply(c, c->argv[1], hascount? shared.nullarray[c->resp]:\
  \ shared.null[c->resp]);\r\n```\r\n\r\nfixing it is a breaking change, but we may\
  \ wanna do that in 7.0\r\n@itamarhaber please ack.\nYes. i also noticed it when\
  \ we introduced LMPOP, i think we can do that in 7.0\nAnother mia culpea - acked.\n\
  ok. @enjoy-binbin if you have time, i'd love a PR"
image: swebench/sweb.eval.x86_64.redis_1776_redis-10095:latest
instance_id: redis__redis-10095
log_parser: parse_log_redis
repo: redis/redis
split: test
version: '10095'
