base_commit: 00c8d1ff1498084c15408cf0014d4c7facdb5dd7
created_at: '2022-02-15 22:06:30'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-3454:latest
instance_id: preactjs__preact-3454
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '3454'
