base_commit: ee76c1eb169897412501d86fbe40122b34cd2e8d
created_at: '2021-01-14 10:31:20'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-2927:latest
instance_id: preactjs__preact-2927
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '2927'
