base_commit: bc0b4880e000b881a1cabc733b2d261f3526d15e
created_at: '2024-07-15 23:26:55'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.uutils_1776_coreutils-6575:latest
instance_id: uutils__coreutils-6575
log_parser: parse_log_cargo
repo: uutils/coreutils
split: test
version: '6575'
