base_commit: 04dd02e71a444fb36019d892fde6948a88aac637
created_at: '2024-11-20 19:27:57'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.rubocop_1776_rubocop-13479:latest
instance_id: rubocop__rubocop-13479
log_parser: parse_log_rspec_transformed_json
repo: rubocop/rubocop
split: test
version: '13479'
