base_commit: 6abfda54c380c07ea0d460706833929654fac25a
created_at: '2023-08-10 04:00:07'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.redis_1776_redis-12472:latest
instance_id: redis__redis-12472
log_parser: parse_log_redis
repo: redis/redis
split: test
version: '12472'
