base_commit: 49e4855c10d8f76faf477f2ceb5ecbdbe2c849a3
created_at: '2023-02-20 20:13:10'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.babel_1776_babel-15445:latest
instance_id: babel__babel-15445
log_parser: parse_log_jest
repo: babel/babel
split: test
version: '15445'
