base_commit: 7e82e44afdf65d585603a2b615e497eefa5b02a9
created_at: '2024-10-18 21:47:03'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.rubocop_1776_rubocop-13362:latest
instance_id: rubocop__rubocop-13362
log_parser: parse_log_rspec_transformed_json
repo: rubocop/rubocop
split: test
version: '13362'
