base_commit: 18d9e42f276f65ba45da02597191ce555bf23cd0
created_at: '2024-03-10 16:20:27'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-7875:latest
instance_id: php-cs-fixer__php-cs-fixer-7875
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '7875'
