base_commit: ce4f56e74ad1087df8bdc019fc09d1b40438e8b3
created_at: '2024-08-30 13:42:08'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.apache_1776_lucene-13704:latest
instance_id: apache__lucene-13704
log_parser: parse_log_gradle_custom
repo: apache/lucene
split: test
version: '13704'
