base_commit: 4a9ae49f3969c4648b5ee000e6692a449e34c2a8
created_at: '2023-10-05 06:47:22'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-48636:latest
instance_id: laravel__framework-48636
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '48636'
