base_commit: 13b0afb7a28adb3149d7125fb2b9c16edbcf8e94
created_at: '2023-12-31 06:31:48'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-4245:latest
instance_id: preactjs__preact-4245
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '4245'
