base_commit: d6213594ca3767f182e8981fde7a119575e94c65
created_at: '2024-09-11 15:23:25'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_tokio-6838:latest
instance_id: tokio-rs__tokio-6838
log_parser: parse_log_cargo
repo: tokio-rs/tokio
split: test
version: '6838'
