base_commit: 0c5a67f4e5bf17a2fffbe3cbb54792a6464b3237
created_at: '2024-05-24 10:29:47'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.nushell_1776_nushell-12950:latest
instance_id: nushell__nushell-12950
log_parser: parse_log_cargo
repo: nushell/nushell
split: test
version: '12950'
