base_commit: bb670ae486579b6121dc21f3dee35a1b50825746
created_at: '2024-09-06 13:29:41'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-52680:latest
instance_id: laravel__framework-52680
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '52680'
