base_commit: e97462d45251c21ffd1ba4fb5db30f3cf6f6cb6c
created_at: '2023-04-14 09:58:06'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_axum-1934:latest
instance_id: tokio-rs__axum-1934
log_parser: parse_log_cargo
repo: tokio-rs/axum
split: test
version: '1934'
