FAIL_TO_PASS:
- errorBoundary > calls the errorBoundary callback
PASS_TO_PASS:
- errorBoundary > catches errors
- errorBoundary > returns error
- errorBoundary > does not leave a stale closure
base_commit: 9457b221fdacd1052ffdb385918e1bab4b10e833
created_at: '2022-08-21 05:51:04'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-3689:latest
instance_id: preactjs__preact-3689
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '3689'
