base_commit: ae003913a39f3bdf9bbbd8f71a1ed681fd044d8b
created_at: '2023-09-12 11:58:18'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.axios_1776_axios-5892:latest
instance_id: axios__axios-5892
log_parser: parse_log_tap
repo: axios/axios
split: test
version: '5892'
