base_commit: 53cf021b813c61cdeace26e863c89f65f6e92abd
created_at: '2022-07-26 16:15:07'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_tokio-4867:latest
instance_id: tokio-rs__tokio-4867
log_parser: parse_log_cargo
repo: tokio-rs/tokio
split: test
version: '4867'
