base_commit: a9f7e676dc03b5008b8483e0937fc27c1af8287f
created_at: '2021-01-01 02:27:31'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-2896:latest
instance_id: preactjs__preact-2896
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '2896'
