base_commit: c7e7b187316a0969c90706b04db35e78b0e2fc09
created_at: '2021-09-05 05:50:43'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jordansissel_1776_fpm-1829:latest
instance_id: jordansissel__fpm-1829
log_parser: parse_log_rspec_transformed_json
repo: jordansissel/fpm
split: test
version: '1829'
