FAIL_TO_PASS:
- com.google.gson.functional.FieldNamingTest#testUpperCaseWithUnderscores
- com.google.gson.functional.NamingPolicyTest#testGsonWithUpperCaseUnderscorePolicySerialization
- com.google.gson.functional.NamingPolicyTest#testGsonWithUpperCaseUnderscorePolicyDeserialiation
PASS_TO_PASS: []
base_commit: 16b42ff5805074126c2e5484450c182773e408a2
created_at: '2021-11-22 03:35:03'
eval_type: pass_and_fail
hints_text: 'Hi, we will volunteer to work on this issue in October/November. For
  the project maintainer, please let us know if this is okay and if you want it fixed. '
image: swebench/sweb.eval.x86_64.google_1776_gson-2024:latest
instance_id: google__gson-2024
log_parser: parse_log_maven
repo: google/gson
split: test
version: '2024'
