base_commit: 0bf186a30279212a44d6818f8db6ddf70baa4d1a
created_at: '2023-09-28 07:03:35'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-48573:latest
instance_id: laravel__framework-48573
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '48573'
