base_commit: 27d7920c015700654bd24807520346eada5f6f38
created_at: '2024-10-06 15:37:11'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-4186:latest
instance_id: phpoffice__phpspreadsheet-4186
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '4186'
