base_commit: 0a85a9662d30139c779ea49a59be30db0f292b5d
created_at: '2024-05-10 15:30:26'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_tokio-6551:latest
instance_id: tokio-rs__tokio-6551
log_parser: parse_log_cargo
repo: tokio-rs/tokio
split: test
version: '6551'
