base_commit: a60603346483da721799ccb3faebcbdd757c5f16
created_at: '2022-01-24 04:36:16'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fluent_1776_fluentd-3608:latest
instance_id: fluent__fluentd-3608
log_parser: parse_log_ruby_unit
repo: fluent/fluentd
split: test
version: '3608'
