base_commit: 7f6a328b4744bbdd5ee07c5eccb3f897390ff982
created_at: '2022-08-08 23:55:07'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-4943:latest
instance_id: caddyserver__caddy-4943
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '4943'
