FAIL_TO_PASS:
- TestCookieFilter
PASS_TO_PASS:
- TestQueryFilter
- TestValidateQueryFilter
- TestValidateCookieFilter
- TestRegexpFilter
- TestHashFilter
base_commit: 7f6a328b4744bbdd5ee07c5eccb3f897390ff982
created_at: '2022-08-08 23:55:07'
eval_type: pass_and_fail
hints_text: |-
  The value of `Cookie` is an array, not a string. So you need to do `>0` I believe, to manipulate the first entry in the array.
  Derp, sorry I'm wrong, we document it as `request>headers>Cookie`. Digging deeper.
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-4943:latest
instance_id: caddyserver__caddy-4943
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '4943'
