FAIL_TO_PASS:
- TestContext2Apply_provisionerDestroyRemoved
PASS_TO_PASS:
- TestContext2Apply_provisionerInterpCount
- TestContext2Apply_provisionerModule
- TestContext2Apply_provisionerCreateFail
- TestContext2Apply_provisionerCreateFailNoId
- TestContext2Apply_provisionerFail
- TestContext2Apply_provisionerFail_createBeforeDestroy
- TestContext2Apply_provisionerFailContinue
- TestContext2Apply_provisionerFailContinueHook
- TestContext2Apply_provisionerDestroy
- TestContext2Apply_provisionerDestroyFail
- TestContext2Apply_provisionerDestroyFailContinue
- TestContext2Apply_provisionerDestroyFailContinueFail
- TestContext2Apply_provisionerDestroyTainted
- TestContext2Apply_provisionerResourceRef
- TestContext2Apply_provisionerSelfRef
- TestContext2Apply_provisionerMultiSelfRef
- TestContext2Apply_provisionerMultiSelfRefSingle
- TestContext2Apply_provisionerExplicitSelfRef
- TestContext2Apply_provisionerForEachSelfRef
- TestContext2Apply_provisionerSensitive
base_commit: 047c1af0b4a9e1e650f3811d011bcb92b2ceb15a
created_at: '2024-08-19 15:55:10'
eval_type: pass_and_fail
hints_text: Thanks for this report!
image: swebench/sweb.eval.x86_64.hashicorp_1776_terraform-35611:latest
instance_id: hashicorp__terraform-35611
log_parser: parse_log_gotest
repo: hashicorp/terraform
split: test
version: '35611'
