base_commit: 047c1af0b4a9e1e650f3811d011bcb92b2ceb15a
created_at: '2024-08-19 15:55:10'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.hashicorp_1776_terraform-35611:latest
instance_id: hashicorp__terraform-35611
log_parser: parse_log_gotest
repo: hashicorp/terraform
split: test
version: '35611'
