base_commit: c0f1db966a2809a13de217b0ec0adc9a29decc79
created_at: '2022-10-13 07:48:35'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fluent_1776_fluentd-3917:latest
instance_id: fluent__fluentd-3917
log_parser: parse_log_ruby_unit
repo: fluent/fluentd
split: test
version: '3917'
