base_commit: df327b8bd56023931cd41e233f8703de7bbaa82c
created_at: '2022-12-15 18:24:58'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.redis_1776_redis-11631:latest
instance_id: redis__redis-11631
log_parser: parse_log_redis
repo: redis/redis
split: test
version: '11631'
