FAIL_TO_PASS:
- TestTreeInvalidParamsType
PASS_TO_PASS:
- TestTreeAddAndGet
- TestTreeWildcard
- TestTreeWildcardConflict
- TestTreeChildConflict
- TestTreeDupliatePath
- TestTreeCatchAllConflict
- TestTreeCatchAllConflictRoot
- TestTreeCatchMaxParams
- TestTreeDoubleWildcard
- TestTreeTrailingSlashRedirect
- TestTreeRootTrailingSlashRedirect
- TestTreeFindCaseInsensitivePath
- TestTreeInvalidNodeType
base_commit: f2bbdfe9f26d84cb994f381050692a9e4553bf75
created_at: '2021-06-19 12:16:48'
eval_type: pass_and_fail
hints_text: Just ran into this as well. Seems the code attempting to expand the capacity
  of the params slice at line 446 in `tree.go` doesn't handle expanding the underlying
  capacity properly.
image: swebench/sweb.eval.x86_64.gin-gonic_1776_gin-2755:latest
instance_id: gin-gonic__gin-2755
log_parser: parse_log_gotest
repo: gin-gonic/gin
split: test
version: '2755'
