base_commit: 35116224d21e16fb863293f9011d1d6c97ed0bf4
created_at: '2023-05-25 12:16:33'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.babel_1776_babel-15649:latest
instance_id: babel__babel-15649
log_parser: parse_log_jest
repo: babel/babel
split: test
version: '15649'
