base_commit: c839a98ff527932fd14460829142c486f4531a7b
created_at: '2023-12-19 06:17:46'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-5995:latest
instance_id: caddyserver__caddy-5995
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '5995'
