base_commit: d45fb9647761c8c208865f71cedb9f2f0dc26f1d
created_at: '2021-08-19 12:58:25'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jekyll_1776_jekyll-8771:latest
instance_id: jekyll__jekyll-8771
log_parser: parse_log_jekyll
repo: jekyll/jekyll
split: test
version: '8771'
