base_commit: 915bfc55cd6217e059b5859b341bab7bdd0874c8
created_at: '2024-11-05 03:25:21'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.phpoffice_1776_phpspreadsheet-4214:latest
instance_id: phpoffice__phpspreadsheet-4214
log_parser: parse_log_phpunit
repo: phpoffice/phpspreadsheet
split: test
version: '4214'
