base_commit: b0ba151102a6c1b2e0e4c419c6482a64677c9b40
created_at: '2024-09-23 15:37:03'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.micropython_1776_micropython-15898:latest
instance_id: micropython__micropython-15898
log_parser: parse_log_micropython_test
repo: micropython/micropython
split: test
version: '15898'
