base_commit: b96004e77ebfb23e7349fa495d2177008186bd42
created_at: '2023-07-28 08:43:19'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.facebook_1776_docusaurus-9183:latest
instance_id: facebook__docusaurus-9183
log_parser: parse_log_jest
repo: facebook/docusaurus
split: test
version: '9183'
