base_commit: 483a03f26c7221f10493d86715985a58e61af967
created_at: '2024-08-09 07:04:27'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.apache_1776_druid-16875:latest
instance_id: apache__druid-16875
log_parser: parse_log_maven
repo: apache/druid
split: test
version: '16875'
