base_commit: 4512be49a9fa55270e9afa632be9ff6c9560c455
created_at: '2024-02-19 23:57:52'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-6115:latest
instance_id: caddyserver__caddy-6115
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '6115'
