FAIL_TO_PASS:
- Nullable Type Declaration Fixer > Fix with data set "multiline function declaration"
PASS_TO_PASS:
- Nullable Type Declaration Fixer > Not defining constructor
- Nullable Type Declaration Fixer > Is risky
- Nullable Type Declaration Fixer > Fixer definitions
- Nullable Type Declaration Fixer > Fixers are final
- Nullable Type Declaration Fixer > Deprecated fixers have correct summary
- Nullable Type Declaration Fixer > Deprecated fixers do not have deprecated successor
- Nullable Type Declaration Fixer > Fixer use insert slices when only insertions are
  performed
- Nullable Type Declaration Fixer > Fixer configuration definitions
- Nullable Type Declaration Fixer > Proper method naming
- Nullable Type Declaration Fixer > Fix with data set "scalar with null"
- Nullable Type Declaration Fixer > Fix with data set "class with null"
- Nullable Type Declaration Fixer > Fix with data set "static null"
- Nullable Type Declaration Fixer > Fix with data set "multiple parameters"
- Nullable Type Declaration Fixer > Fix with data set "class properties"
- Nullable Type Declaration Fixer > Fix with data set "skips more than two atomic
  types"
- Nullable Type Declaration Fixer > Fix with data set "skips already fixed"
- Nullable Type Declaration Fixer > Fix with data set "space after ?"
- Nullable Type Declaration Fixer > Fix with data set "no space before ?"
- Nullable Type Declaration Fixer > Fix with data set "readonly property"
- Nullable Type Declaration Fixer > Fix with data set "readonly property with union
  syntax expected"
- Nullable Type Declaration Fixer > Fix with data set "skips DNF types"
- Nullable Type Declaration Fixer > Fix with data set "standalone null"
base_commit: ae2b729efb3507871ddf501424b1a92db4e5b16a
created_at: '2024-12-26 17:33:20'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-8331:latest
instance_id: php-cs-fixer__php-cs-fixer-8331
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '8331'
