base_commit: c77e6284c199761d59467d8cc596a2f03540e72c
created_at: '2022-06-14 14:44:56'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-3567:latest
instance_id: preactjs__preact-3567
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '3567'
