base_commit: ab6ef0b257e4c7aafec0518d93bea3e9c4b75b75
created_at: '2020-03-06 11:52:28'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jekyll_1776_jekyll-8047:latest
instance_id: jekyll__jekyll-8047
log_parser: parse_log_jekyll
repo: jekyll/jekyll
split: test
version: '8047'
