base_commit: 198f4385d2f72ccdd853825270f601bea7a7a190
created_at: '2024-06-04 06:55:59'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-6370:latest
instance_id: caddyserver__caddy-6370
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '6370'
