base_commit: bb851e235dfbe1f197388aea3e7f0eeb1b50c4e3
created_at: '2022-10-01 00:35:01'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.jekyll_1776_jekyll-9141:latest
instance_id: jekyll__jekyll-9141
log_parser: parse_log_jekyll
repo: jekyll/jekyll
split: test
version: '9141'
