base_commit: 25a8d576717f4a69290d6f6755b4a90cfaab08ff
created_at: '2024-03-26 16:26:46'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prometheus_1776_prometheus-13845:latest
instance_id: prometheus__prometheus-13845
log_parser: parse_log_gotest
repo: prometheus/prometheus
split: test
version: '13845'
