FAIL_TO_PASS:
- TestRangeQuery
- TestRangeQuery/drop-metric-name
- TestLabels_DropMetricName
PASS_TO_PASS:
- TestRangeQuery/sum_over_time_with_all_values
- TestRangeQuery/sum_over_time_with_trailing_values
- TestRangeQuery/sum_over_time_with_all_values_long
- TestRangeQuery/sum_over_time_with_all_values_random
- TestRangeQuery/metric_query
- TestRangeQuery/metric_query_with_trailing_values
- TestRangeQuery/short-circuit
- TestLabels_String
- TestLabels_MatchLabels
- TestLabels_HasDuplicateLabelNames
- TestLabels_WithoutEmpty
- TestLabels_WithoutEmpty/#00
- TestLabels_WithoutEmpty/#01
- TestLabels_WithoutEmpty/#02
- TestLabels_WithoutEmpty/#03
- TestLabels_WithoutEmpty/#04
- TestLabels_WithoutEmpty/#05
- TestLabels_IsValid
- TestLabels_IsValid/#00
- TestLabels_IsValid/#01
- TestLabels_IsValid/#02
- TestLabels_IsValid/#03
- TestLabels_IsValid/#04
- TestLabels_IsValid/#05
- TestLabels_IsValid/#06
- TestLabels_IsValid/#07
- TestLabels_IsValid/#08
- TestLabels_Equal
- TestLabels_FromStrings
- TestLabels_Compare
- TestLabels_Has
- TestLabels_Get
- TestLabels_Copy
- TestLabels_Map
- TestLabels_BytesWithLabels
- TestLabels_BytesWithoutLabels
- TestLabels_Hash
base_commit: 25a8d576717f4a69290d6f6755b4a90cfaab08ff
created_at: '2024-03-26 16:26:46'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.prometheus_1776_prometheus-13845:latest
instance_id: prometheus__prometheus-13845
log_parser: parse_log_gotest
repo: prometheus/prometheus
split: test
version: '13845'
