base_commit: af86aee6b86a99736ca304ff656d0e4c6d547333
created_at: '2024-09-09 22:14:37'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.uutils_1776_coreutils-6690:latest
instance_id: uutils__coreutils-6690
log_parser: parse_log_cargo
repo: uutils/coreutils
split: test
version: '6690'
