base_commit: 3799f7f3118d57dc5d3dfaabde69a912fff65a7e
created_at: '2023-02-23 07:02:26'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-46234:latest
instance_id: laravel__framework-46234
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '46234'
