base_commit: 5c9cb78beb156b501c25e571739982f05aab90c9
created_at: '2024-10-17 23:08:19'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-53206:latest
instance_id: laravel__framework-53206
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '53206'
