base_commit: 3780b41dd070436f3f55327b0a88f27a52e2dfa8
created_at: '2023-12-08 22:24:37'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.nlohmann_1776_json-4237:latest
instance_id: nlohmann__json-4237
log_parser: parse_log_doctest
repo: nlohmann/json
split: test
version: '4237'
