FAIL_TO_PASS:
- ignored_suffix_arg
PASS_TO_PASS: []
base_commit: 59d4cfb75c1a17a26b2b38956ee08d8c53f04e04
created_at: '2021-10-09 19:15:07'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.sharkdp_1776_bat-1892:latest
instance_id: sharkdp__bat-1892
log_parser: parse_log_cargo
repo: sharkdp/bat
split: test
version: '1892'
