base_commit: 3ac290c1a551bd6aaf2c2cc46cec1e42facae0e4
created_at: '2024-12-17 19:44:29'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-53949:latest
instance_id: laravel__framework-53949
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '53949'
