base_commit: 840ec8569ddb304345f082bb82d733742f431504
created_at: '2022-12-24 01:17:13'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fmtlib_1776_fmt-3248:latest
instance_id: fmtlib__fmt-3248
log_parser: parse_log_googletest
repo: fmtlib/fmt
split: test
version: '3248'
