base_commit: 950bb820237d52e15690408083e328f739ac0ef3
created_at: '2022-09-10 11:00:24'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fastlane_1776_fastlane-20642:latest
instance_id: fastlane__fastlane-20642
log_parser: parse_log_rspec_transformed_json
repo: fastlane/fastlane
split: test
version: '20642'
