base_commit: eadd030370cc62807c22fbb1af3663e98e293f8c
created_at: '2021-08-04 17:03:57'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fastlane_1776_fastlane-19207:latest
instance_id: fastlane__fastlane-19207
log_parser: parse_log_rspec_transformed_json
repo: fastlane/fastlane
split: test
version: '19207'
