base_commit: 2cafedee2ddf7c73795e887ef1970df4be2bca90
created_at: '2022-09-19 13:54:47'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-3739:latest
instance_id: preactjs__preact-3739
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '3739'
