FAIL_TO_PASS:
- Total > Absolute diff
PASS_TO_PASS:
- 'Total > Returns total value with data set #0'
- 'Total > Returns total value with data set #1'
- 'Total > Returns total value with data set #2'
- 'Total > Returns total value with data set #3'
- 'Total > Returns total value with data set #4'
- 'Total > Returns total value with data set #5'
- 'Total > Returns total value with data set #6'
- 'Total > Returns total value with data set #7'
- 'Total > Returns total value with data set #8'
- 'Total > Returns total value with data set #9'
- 'Total > Returns total value with data set #10'
- 'Total > Returns total value with data set #11'
- 'Total > Returns total value with data set #12'
- 'Total > Returns total value with data set #13'
- 'Total > Returns total value with data set #14'
- 'Total > Returns total value with data set #15'
- Total > Throws exception for invalid units
- Total > Get totals via getters
- 'Total > Get negative totals via getters with data set #0'
- 'Total > Get negative totals via getters with data set #1'
- 'Total > Get negative totals via getters with data set #2'
- Total > Totals with custom factors
- Total > Float hours factors
- Total > Float days factors
- Total > Float in multiple factors
- Total > Get totals via getters with custom factors
- Total > Get totals via getters with false factor
- Total > Microseconds interval
- Total > With diff interval
- Total > Alteration after diff
base_commit: da64770bf83ac06914418db7df14dadd4ded0212
created_at: '2024-10-04 13:00:39'
eval_type: pass_and_fail
hints_text: "Hello,\r\n\r\nThanks for the report. The analysis is also correct, comparison\
  \ of `CarbonInterval` is using `->totalMicroseconds` and it's being negative in\
  \ this case:\r\n\r\n```php\r\n$diff = Carbon::now()->addDays(15)->diff(Carbon::now(),\
  \ true);\r\nvar_dump($diff->totalMicroseconds, CarbonInterval::minutes(30)->totalMicroseconds);\r\
  \n```\r\n\r\n=>\r\n```\r\ndouble(-1295999999048)\r\ndouble(1800000000)\r\n```\r\n\
  \r\nI will investigate further.\r\n\r\nAs a work-around in the meantime you can\
  \ use `abs($interval->totalMicroseconds)` and compare them."
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-3073:latest
instance_id: briannesbitt__carbon-3073
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '3073'
