base_commit: da64770bf83ac06914418db7df14dadd4ded0212
created_at: '2024-10-04 13:00:39'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-3073:latest
instance_id: briannesbitt__carbon-3073
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '3073'
