base_commit: b8ca298a5475497d01b194ed5688441454d8ee34
created_at: '2024-08-11 18:32:17'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-52451:latest
instance_id: laravel__framework-52451
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '52451'
