base_commit: 7556b61bd0d9f72bbd906c3abaebf2b1c9aeacbf
created_at: '2021-03-14 11:17:30'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-3062:latest
instance_id: preactjs__preact-3062
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '3062'
