base_commit: 960150bb034dc9a549ee7289b1a4eb4abafeb30a
created_at: '2023-02-26 20:33:33'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.caddyserver_1776_caddy-5404:latest
instance_id: caddyserver__caddy-5404
log_parser: parse_log_gotest
repo: caddyserver/caddy
split: test
version: '5404'
