base_commit: 2b9d25df052e50c60531b1000703b79bf9b6065a
created_at: '2019-05-10 19:03:15'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sharkdp_1776_bat-562:latest
instance_id: sharkdp__bat-562
log_parser: parse_log_cargo
repo: sharkdp/bat
split: test
version: '562'
