base_commit: f0a95a77782538eafca6c4d2f2f2792be3dbbfcf
created_at: '2024-06-10 18:21:26'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-8075:latest
instance_id: php-cs-fixer__php-cs-fixer-8075
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '8075'
