base_commit: 28e5ddb075b61525ba686f3ed6ecbf7f762fc558
created_at: '2023-08-21 04:59:10'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.projectlombok_1776_lombok-3486:latest
instance_id: projectlombok__lombok-3486
log_parser: parse_log_ant
repo: projectlombok/lombok
split: test
version: '3486'
