base_commit: 5512ebcd23d261a2be5ee07676721b7637ffc054
created_at: '2022-01-01 02:57:12'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_axum-682:latest
instance_id: tokio-rs__axum-682
log_parser: parse_log_cargo
repo: tokio-rs/axum
split: test
version: '682'
