base_commit: 4c7850844e218b4fa25e29c83bc80b7ef06836cb
created_at: '2024-09-20 10:34:46'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.laravel_1776_framework-52866:latest
instance_id: laravel__framework-52866
log_parser: parse_log_phpunit
repo: laravel/framework
split: test
version: '52866'
