base_commit: db0f4f2e7a2338ea40050f623f05505a798fc1a4
created_at: '2024-07-06 22:32:36'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.preactjs_1776_preact-4436:latest
instance_id: preactjs__preact-4436
log_parser: parse_log_karma
repo: preactjs/preact
split: test
version: '4436'
