FAIL_TO_PASS:
- supports http with nodejs FormData SpecCompliant FormData should allow passing FormData
PASS_TO_PASS:
- supports http with nodejs FormData form-data instance (https://www.npmjs.com/package/form-data)
  should allow passing FormData
- supports http with nodejs FormData toFormData helper should properly serialize nested
  objects for parsing with multer.js (express.js)
base_commit: 65e8d1e28ce829f47a837e45129730e541950d3c
created_at: '2022-11-27 18:02:03'
eval_type: pass_and_fail
hints_text: ''
image: swebench/sweb.eval.x86_64.axios_1776_axios-5316:latest
instance_id: axios__axios-5316
log_parser: parse_log_tap
repo: axios/axios
split: test
version: '5316'
