base_commit: b3d0d94a1aab70d5580742659ae45177cec5ebcb
created_at: '2024-06-20 13:33:58'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.briannesbitt_1776_carbon-3041:latest
instance_id: briannesbitt__carbon-3041
log_parser: parse_log_phpunit
repo: briannesbitt/carbon
split: test
version: '3041'
