base_commit: fcbcb567c93f8aff3e817371c18dc98b2a5094ff
created_at: '2023-09-26 10:49:56'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fluent_1776_fluentd-4311:latest
instance_id: fluent__fluentd-4311
log_parser: parse_log_ruby_unit
repo: fluent/fluentd
split: test
version: '4311'
