base_commit: 9f598a31aafb92d675f38f1c8371e4ac76f858bf
created_at: '2024-01-04 01:49:47'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.gin-gonic_1776_gin-3820:latest
instance_id: gin-gonic__gin-3820
log_parser: parse_log_gotest
repo: gin-gonic/gin
split: test
version: '3820'
