base_commit: b4204e223dc96df3d51fc8893f32d37b66be7005
created_at: '2023-01-31 21:46:10'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.tokio-rs_1776_axum-1730:latest
instance_id: tokio-rs__axum-1730
log_parser: parse_log_cargo
repo: tokio-rs/axum
split: test
version: '1730'
