base_commit: db66e4459bc4e66c03629d7cbc235f59245280c0
created_at: '2024-01-21 16:24:00'
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sharkdp_1776_bat-2835:latest
instance_id: sharkdp__bat-2835
log_parser: parse_log_cargo
repo: sharkdp/bat
split: test
version: '2835'
