FAIL_TO_PASS:
- TestEvaluations
- TestEvaluations/testdata/functions.test
PASS_TO_PASS:
- TestEvaluations/testdata/aggregators.test
- TestEvaluations/testdata/at_modifier.test
- TestEvaluations/testdata/collision.test
- TestEvaluations/testdata/histograms.test
- TestEvaluations/testdata/literals.test
- TestEvaluations/testdata/operators.test
- TestEvaluations/testdata/selectors.test
- TestEvaluations/testdata/staleness.test
- TestEvaluations/testdata/subquery.test
- TestEvaluations/testdata/trig_functions.test
base_commit: 89de30a0b754f4eb54fb543037683f3db6cda109
created_at: '2022-05-20 10:31:28'
eval_type: pass_and_fail
hints_text: "cc @juliusv \nSure, sounds good to me.\nI would like to take this one.\n\
  > I would like to take this one.\r\n\r\nSure, have fun :-) \U0001F44D\U0001F3FC "
image: swebench/sweb.eval.x86_64.prometheus_1776_prometheus-10720:latest
instance_id: prometheus__prometheus-10720
log_parser: parse_log_gotest
repo: prometheus/prometheus
split: test
version: '10720'
