base_commit: c18d01c03cf22b82ff5e2e03f01e59f956684708
created_at: '2024-02-07 11:00:58'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.fastlane_1776_fastlane-21857:latest
instance_id: fastlane__fastlane-21857
log_parser: parse_log_rspec_transformed_json
repo: fastlane/fastlane
split: test
version: '21857'
