base_commit: efe7a396a3e5434123011a808cf8d57681713530
created_at: '2024-05-08 21:51:48'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.php-cs-fixer_1776_php-cs-fixer-7998:latest
instance_id: php-cs-fixer__php-cs-fixer-7998
log_parser: parse_log_phpunit
repo: php-cs-fixer/php-cs-fixer
split: test
version: '7998'
