base_commit: 1df53d6eb30a019fff69a5ff7533ebbd998a438d
created_at: '2023-11-20 13:48:30'
datasets:
- SWE-bench/SWE-bench_Multilingual
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.apache_1776_druid-15402:latest
instance_id: apache__druid-15402
log_parser: parse_log_maven
repo: apache/druid
split: test
version: '15402'
